/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSkillGapRouteImport } from './routes/_authenticated/skill-gap'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedJdMatchRouteImport } from './routes/_authenticated/jd-match'
import { Route as AuthenticatedInterviewSetupRouteImport } from './routes/_authenticated/interview-setup'
import { Route as AuthenticatedInterviewRoomRouteImport } from './routes/_authenticated/interview-room'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiMonitorRouteImport } from './routes/_authenticated/ai-monitor'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSkillGapRoute = AuthenticatedSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJdMatchRoute = AuthenticatedJdMatchRouteImport.update({
  id: '/jd-match',
  path: '/jd-match',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewSetupRoute =
  AuthenticatedInterviewSetupRouteImport.update({
    id: '/interview-setup',
    path: '/interview-setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewRoomRoute =
  AuthenticatedInterviewRoomRouteImport.update({
    id: '/interview-room',
    path: '/interview-room',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiMonitorRoute = AuthenticatedAiMonitorRouteImport.update({
  id: '/ai-monitor',
  path: '/ai-monitor',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai-monitor': typeof AuthenticatedAiMonitorRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/interview-room': typeof AuthenticatedInterviewRoomRoute
  '/interview-setup': typeof AuthenticatedInterviewSetupRoute
  '/jd-match': typeof AuthenticatedJdMatchRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/results': typeof AuthenticatedResultsRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/ai-monitor': typeof AuthenticatedAiMonitorRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/interview-room': typeof AuthenticatedInterviewRoomRoute
  '/interview-setup': typeof AuthenticatedInterviewSetupRoute
  '/jd-match': typeof AuthenticatedJdMatchRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/results': typeof AuthenticatedResultsRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/ai-monitor': typeof AuthenticatedAiMonitorRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/interview-room': typeof AuthenticatedInterviewRoomRoute
  '/_authenticated/interview-setup': typeof AuthenticatedInterviewSetupRoute
  '/_authenticated/jd-match': typeof AuthenticatedJdMatchRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skill-gap': typeof AuthenticatedSkillGapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/ai-monitor'
    | '/analytics'
    | '/audit'
    | '/dashboard'
    | '/history'
    | '/interview-room'
    | '/interview-setup'
    | '/jd-match'
    | '/panel'
    | '/results'
    | '/resume'
    | '/settings'
    | '/skill-gap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/ai-monitor'
    | '/analytics'
    | '/audit'
    | '/dashboard'
    | '/history'
    | '/interview-room'
    | '/interview-setup'
    | '/jd-match'
    | '/panel'
    | '/results'
    | '/resume'
    | '/settings'
    | '/skill-gap'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/ai-monitor'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/interview-room'
    | '/_authenticated/interview-setup'
    | '/_authenticated/jd-match'
    | '/_authenticated/panel'
    | '/_authenticated/results'
    | '/_authenticated/resume'
    | '/_authenticated/settings'
    | '/_authenticated/skill-gap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/skill-gap': {
      id: '/_authenticated/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof AuthenticatedSkillGapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jd-match': {
      id: '/_authenticated/jd-match'
      path: '/jd-match'
      fullPath: '/jd-match'
      preLoaderRoute: typeof AuthenticatedJdMatchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview-setup': {
      id: '/_authenticated/interview-setup'
      path: '/interview-setup'
      fullPath: '/interview-setup'
      preLoaderRoute: typeof AuthenticatedInterviewSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview-room': {
      id: '/_authenticated/interview-room'
      path: '/interview-room'
      fullPath: '/interview-room'
      preLoaderRoute: typeof AuthenticatedInterviewRoomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-monitor': {
      id: '/_authenticated/ai-monitor'
      path: '/ai-monitor'
      fullPath: '/ai-monitor'
      preLoaderRoute: typeof AuthenticatedAiMonitorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiMonitorRoute: typeof AuthenticatedAiMonitorRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInterviewRoomRoute: typeof AuthenticatedInterviewRoomRoute
  AuthenticatedInterviewSetupRoute: typeof AuthenticatedInterviewSetupRoute
  AuthenticatedJdMatchRoute: typeof AuthenticatedJdMatchRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillGapRoute: typeof AuthenticatedSkillGapRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiMonitorRoute: AuthenticatedAiMonitorRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInterviewRoomRoute: AuthenticatedInterviewRoomRoute,
  AuthenticatedInterviewSetupRoute: AuthenticatedInterviewSetupRoute,
  AuthenticatedJdMatchRoute: AuthenticatedJdMatchRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillGapRoute: AuthenticatedSkillGapRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
